# Generated by Django 2.1 on 2018-12-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0003_auto_20181218_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
