# Generated by Django 2.1 on 2018-12-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0004_quote_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_time_code',
            field=models.DateField(null=True),
        ),
    ]
