# Generated by Django 2.1 on 2018-12-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0005_auto_20181222_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='model',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='model_orientation',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
