# Generated by Django 2.1 on 2018-12-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0006_auto_20181222_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='model',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='model_orientation',
        ),
        migrations.AddField(
            model_name='quote',
            name='model_orientation_path',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='model_path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
