# Generated by Django 2.1 on 2018-12-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0009_client_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
