# Generated by Django 2.1.5 on 2019-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0012_auto_20190124_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='client_id',
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
