# Generated by Django 2.1.5 on 2019-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0013_auto_20190124_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
