# Generated by Django 2.1.5 on 2019-01-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0014_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='key',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
