# Generated by Django 2.1.5 on 2019-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0016_auto_20190124_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='job_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
