# Generated by Django 2.1.5 on 2019-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigg', '0017_auto_20190129_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='job_number',
            field=models.IntegerField(null=True),
        ),
    ]
